# Generated by Django 6.0.4 on 2026-04-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rappapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicedetail',
            name='price_at_order',
        ),
        migrations.AddField(
            model_name='invoicedetail',
            name='method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('MOMO', 'MoMo'), ('STRIPE', 'Stripe'), ('PAYPAL', 'PayPal'), ('ZALOPAY', 'ZaloPay')], default='CASH', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoicedetail',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoicedetail',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
