# Generated by Django 6.0.4 on 2026-04-16 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rappapi', '0002_alter_rate_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Dishes'},
        ),
    ]
