# Generated by Django 6.0.4 on 2026-04-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rappapi', '0002_remove_invoicedetail_price_at_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicedetail',
            name='method',
        ),
        migrations.RemoveField(
            model_name='invoicedetail',
            name='status',
        ),
        migrations.RemoveField(
            model_name='invoicedetail',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='invoice',
            name='method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('MOMO', 'MoMo'), ('STRIPE', 'Stripe'), ('PAYPAL', 'PayPal'), ('ZALOPAY', 'ZaloPay')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
