# Generated by Django 6.0.4 on 2026-04-28 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rappapi', '0003_remove_invoicedetail_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Trống'), ('OCCUPIED', 'Đang ngồi'), ('BOOKED', 'Check-in')], default='AVAILABLE', max_length=15),
        ),
    ]
