# Generated by Django 6.0.4 on 2026-04-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rappapi', '0005_alter_invoice_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
