# Generated by Django 6.0.4 on 2026-05-15 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rappapi', '0006_alter_invoice_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Trống'), ('BOOKED', 'Đã đặt'), ('OCCUPIED', 'Đang ăn')], default='AVAILABLE', max_length=15),
        ),
        migrations.CreateModel(
            name='TableBook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Trống'), ('BOOKED', 'Đã đặt'), ('OCCUPIED', 'Đang ăn')], default='BOOKED', max_length=15)),
                ('note', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(limit_choices_to={'customer__isnull': False}, on_delete=django.db.models.deletion.CASCADE, related_name='table_books', to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='Rappapi.table')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
    ]
